version: "3.8"
services:
  sw-system-backend:
    image: sw-system-backend
    container_name: sw-system-backend
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      HOST: ${HOST}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - "postgres"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ${DB_STORE_VOLUME}:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/10-init.sql
